### ISSUE TITLE
Update the doc to matching current architecture

### ISSUE THREAD

**Issue by xinifinity** [ava-labs/firewood#191]
With the new feature and a bunch of changes, we need to update the doc to reflect these.

**Comment by rkuris** [comment]
@xinifinity which docs are outdated, or is this just a generic request to review them all for anything that doesn't reference Proposals?

**Comment by xinifinity** [comment]
Actually with a few previous fix,  this is now a dup of https://github.com/ava-labs/firewood/issues/266
