### ISSUE TITLE
Properly separate unit and integration tests

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#255]
Anything with the filesystem should be considered an integration test. However, there will likely be some exceptions where we want to test things that aren't just part of the public API
https://doc.rust-lang.org/cargo/reference/cargo-targets.html#integration-tests

Writing tests as integration tests (where appropriate) help speed up compile times and have a nice and clear distinction in the test reports

**Comment by rkuris** [comment]
@richardpringle please add to the description so someone can pick this up easily

**Comment by richardpringle** [comment]
> @richardpringle please add to the description so someone can pick this up easily

done

**Comment by rkuris** [comment]
Timing will be important here. See https://github.com/ava-labs/firewood/pull/390 for an example of what needs to be done.

**Comment by rkuris** [comment]
Fixed by new design
