### ISSUE TITLE
Make `ObjRef` actually borrow data

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#290]
Right now, `ObjRef`'s lifetime is simply a lifetime specified in `PhantomData` that gets set to the lifetime of the borrow of the `ShaleStore`. I'm guessing that the reason for this is that you're supposed to treat `ObjRef` as invalid if the `ShaleStore` has been dropped, even though the `ObjRef` could actually contain the last living reference to the `ObjectCache` and contain real-data that you could operate on with no UB. IMO, this is a completely improper use of Rust lifetimes and should be fixed. `ObjRef` should contain a reference to the borrowed data and a borrowed `ObjectCache`.

If you are going to take on this issue, please discuss your planned approach here, before attempting to solve.

**Comment by richardpringle** [comment]
@rkuris, my bad, I said you could close this when it wasn't true. `ObjRef` now borrows the cache, but not the data, unfortunately. There's still more work to be done here.

**Comment by rkuris** [comment]
done? :)
