### ISSUE TITLE
[Request] Don't exclusively rely on io_uring

### ISSUE THREAD

**Issue by kayabaNerve** [ava-labs/firewood#297]
> Firewood currently is Linux-only, as it has a dependency on the asynchronous I/O provided by the Linux kernel (see libaio). Unfortunately, Docker is not able to successfully emulate the syscalls libaio relies on, so Linux or a Linux VM must be used to run Firewood. We intend to migrate to io_uring which should allow for this emulation.

Ideally, the backend is modular, enabling usage of libaio OR io_uring OR (another platform's async IO system). I say this not only for diversity of systems which firewood can run on (from older Linuxes to other POSIXs to Windows), yet also for the security of the Linux systems firewood runs on.

io_uring has notable security issues, justifying its disabling by Google across a variety of systems: https://security.googleblog.com/2023/06/learnings-from-kctf-vrps-42-linux.html

While async IO backend flexibility may already be planned, the README discusses a 'migration to' (not an "option of"), and https://github.com/ava-labs/firewood/issues/41 discussed removing aio with further usage being built of rio (io_uring) (not feature-flagging between them). Accordingly, I'd like to raise this concern and ask for clarification of intent regarding the future of firewood's async IO.

**Comment by kayabaNerve** [comment]
I am referring to the README, L129 and L130. I would love to hear firewood can be run in Docker as that would enable me to start exploring it.

I have no objections to an io_uring backend, *even if* it's less secure and ensuring its security is *out of scope* (see Google only allowing io_uring for trusted applications, creating the argument all Firewood applications must be trusted). I definitely appreciate the desire to maximize performance. I solely wanted to voice my desire for keeping options open, not moving from X to solely Y. Happy to hear that sounds amenable :)

**Comment by rkuris** [comment]
Hi @kayabaNerve -- your concerns about io_uring are definitely heard! We will change our approach to support pluggable IO subsystems instead, perhaps driven by feature flags.

libaio is giving us a little trouble with durability and write ordering so if we want to keep it, it will take some effort to improve it.

**Comment by rkuris** [comment]
Closing this issue as there is no actual work to do on this issue. I further updated the readme to clarify our intent here; we want fully pluggable IO with async context. Exactly what gets used will be configurable.
