### ISSUE TITLE
Choice of license

### ISSUE THREAD

**Issue by kayabaNerve** [ava-labs/firewood#315]
Is there any plans to move from the "Ecosystem License" to any FOSS license? I was just about to start trying Firewood out, benchmarking it, and looking through its API (planning to submit PRs if I noted anything) when I noticed I can only legally use this in connection with Avalanche. I'm not even sure I *can* experiment with it/benchmark it due to my lack of an Avalanche related use case. I also have no interest in contributing to non-FOSS work.

I'd recommend either MIT, Apache 2.0, or one of the GPLs, yet I know this is a complicated business/legal decision which won't be immediately decided on/resolved.

**Comment by patrick-ogrady** [comment]
There are not any plans to migrate Firewood away from the [Ecosystem License](https://github.com/ava-labs/firewood/blob/main/LICENSE.md) at this time. Ava Labs is developing this tool exclusively for projects in the Avalanche Ecosystem to use however they fit.

If that changes, I'll update this thread (our usual preference for things like this is BSD-3).
