### ISSUE TITLE
Use a more efficient key-type

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#326]
We do a ton of stuff with keys where we have to copy the key around and save a subset of the key in the node itself. It would be super beneficial if we could avoid allocations and use stack values instead. 

One option would be to use [`smallvec`](https://crates.io/crates/smallvec), which seems to be one of the better-maintained implementations of its kind (vs `tinyvec` and `arrayvec`). 

We could further limit the amount of compression of `PartialPath` at an arbitrary number (64 bytes, for instance). This would allow users to use keys of their own liking (in other words, they could choose to use `smallvec` if they want the optimization), and we could limit the amount of *splitting **and** allocating* inside the `Merkle` implementation.

**Comment by rkuris** [comment]
Keys also are rarely growing or shrinking, so perhaps switching to Box<[u8]> as suggested in #353 is a good thing to do in combination with this.

**Comment by rkuris** [comment]
Fixed
