### ISSUE TITLE
Clean up public api for `merkle` mod

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#362]
pub(crate) or pub(super). We don't want these as part of the public API.

_Originally posted by @rkuris in https://github.com/ava-labs/firewood/pull/360#discussion_r1399830276_

              nit: LeafNode shouldn't escape the crate, so the inner ones can just be pub, but this one should be `pub(crate)`.

_Originally posted by @rkuris in https://github.com/ava-labs/firewood/pull/360#discussion_r1401018883_

**Comment by rkuris** [comment]
Fixed with new design
