### ISSUE TITLE
Move `encode_regression_test` from `leaf.rs` to `partial_path.rs` with necessary changes

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#365]
Is this just testing `partial_path`? If you're checking to see if the node is storing it correctly, rather than hardcoding this here (which can change if partial_path changes), perhaps use partial_path and compare that encoding?

_Originally posted by @rkuris in https://github.com/ava-labs/firewood/pull/360#discussion_r1400990131_

**Comment by rkuris** [comment]
No longer a factor with new design
