### ISSUE TITLE
Remove `From<Vec<u8>>` implementation from `PartialPath`

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#366]
It's now too easy for someone to put non-nibbles into a PartialPath.

This also ties PartialPath more strongly to a Vec, which is something I'd like to change.

_Originally posted by @rkuris in https://github.com/ava-labs/firewood/pull/360#discussion_r1400980154_

 - [ ] Remove `From<Vec<u8>>` implementation
 - [ ] Make it easier to extend a `PartialPath`
 - [ ] Make it easier to shorten a `PartialPath`
 - [x] Consider using smallvec or tinyvec to reduce allocations

**Comment by rkuris** [comment]
`PartialPath` has been completely revamped with new design
