### ISSUE TITLE
Move `tests/merkle.rs` to `src/merkle.rs`

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#398]
This should be done in two stages 
 - [ ] 1) move tests to `src/merkle/merkle_tests.rs` with `#[cfg(test)] mod merkle_tests;` 
    - [ ] make the `crate::merkle` mod `pub(crate)` so that we don't leak our abstractions
 - [ ] 2)migrate each test to `merkle::tests` mod defined in the `src/merkle.rs` file. 
 
 The reason for doing this in two stages is that the tests in `tests/merkle.rs`, blindly builds the merkle-tree [here](https://github.com/ava-labs/firewood/blob/8799910035817e0574d02f516fbb73f0d52b907b/firewood/tests/merkle.rs#L17), without checking that the keys do in fact get inserted properly into the tree. Also, a bunch of the "fuzz" tests, aren't proper fuzz-tests at all since they use the exact same seed. The tests are useful, but we should use a proper fuzz-testing framework.
 
 A final open question is how should the fuzz-tests be run? Should we run tests that are not deterministic in CI on every PR? That seems like a bad idea, but I'm open to opinions here.

**Comment by rkuris** [comment]
Fixed with new design and structure
