### ISSUE TITLE
Remove Extra Option From Children (`DiskAddress`)

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#411]
Upon further review, I don't think that we should do this. It doesn't make sense to have an uninitialized `DiskAddress`. The only valid place that I see this happening is related to `Extension` nodes and currently, calling `serialize` on a `DiskAddress` that has not been initialized will panic. 

Instead, `DiskAddress` should simply wrap `NonZeroUsize`, and parent types can use `Option<DiskAddress>`.

_Originally posted by @richardpringle in https://github.com/ava-labs/firewood/pull/341#pullrequestreview-1730893677_

First, we need to explore whether or not there's any valid use case for `DiskAddress::null()` aside from an uninitialized value. I would argue that dealing with uninitialized values should be on the caller instead of blindly passing around disk-addresses that may or may not be initialized. 

We need to spike on first though, it's possible that something funky is going on with `DiskAddress::null()`. If that's the case, we can capture that in this issue and determine the best solution (could be to remove the `Option` from the `children` array on branch-nodes.

**Comment by rkuris** [comment]
Resolved with new design
