### ISSUE TITLE
Differentiate between empty data and no data for Bincode encode schema

### ISSUE THREAD

**Issue by xinifinity** [ava-labs/firewood#433]
As mentioned [here](https://github.com/ava-labs/firewood/pull/425#discussion_r1424432630) fix https://github.com/ava-labs/firewood/blob/main/firewood/src/merkle/node.rs#L590 and https://github.com/ava-labs/firewood/blob/main/firewood/src/merkle/node/branch.rs#L119.

**Comment by rkuris** [comment]
No longer using bincode with new design
