### ISSUE TITLE
Add `sentinal_node_address` to `Merkle`

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#439]
We have a ton of `Merkle` methods that require passing in either a disk-address for the sentinel-node, or a reference to the node. *I suspect* that we never pass in anything other than the sentinel node or its address. We should just keep the address as a property of `Merkle` so that we don't need to pass it in to all the methods. 

I think this goes hand-in-hand with initializing the sentinel node on instantiation of the `Merkle` struct too.

**Comment by rkuris** [comment]
Fixed by new design
