### ISSUE TITLE
Large Key Support 

### ISSUE THREAD

**Issue by xinifinity** [ava-labs/firewood#469]
Currently we don't have a limit on the key size, we may want to,
- examine the code base to see cases where large key are not handled carefully, to avoid copying large keys around. See comment https://github.com/ava-labs/firewood/pull/465/files#r1442283589.
- put a limit on proofs size (to avoid large proof sending over networks), we can limit it to a certain size e.g. 4MB. which has an implication on the limit how big the key should be.

**Comment by rkuris** [comment]
I think a good fix for this is a `api::Error::KeyTooLarge` error which has the length of the key that was too large, and we just return that. We can have a const somewhere that specifies the largest allowable key. If someone wants to deal with really big keys, they can set this to some really big value and rebuild things, suffering the performance penalty the whole time
