### ISSUE TITLE
`is_encoded_longer_than_hash_len` is actually longer-than-or-equal-to

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#508]
Hmm, `is_encoded_longer_than_hash_len` is a bad naming, do you mind changed it to `is_encoded_longer_than_or_equal_to_hash_len` or keep it as it is an update `node::is_encoded_longer_than_hash_len()` to really reflect the naming. Thanks!

_Originally posted by @xinifinity in https://github.com/ava-labs/firewood/pull/505#discussion_r1470281465_
            
I think it would actually be better to make this `is_shorter_than_hash` as that is the less common case and adjust the code accordingly.

**Comment by rkuris** [comment]
fixed by redesign. Proof nodes aren't the same as regular nodes any more.
