### ISSUE TITLE
Use `test-matrix` macro to assure all cases are covered with encoding/decoding nodes with the `BinarySerde` codecs

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/firewood#512]
This test case is currently missing:
```rust
#[test_case(Bincode::new(), branch(b"value", Some(Vec::new())); "branch with empty chd with Bincode")]
``` 
and currently fails. 

Using `test-matrix` will ensure that we don't miss cases like this. 

It's unclear whether or not we need to fix the issue, as an empty vector is not a valid encoded child.

**Comment by rkuris** [comment]
Obsoleted by new design, no longer using serde for serialization/deserialization
