### ISSUE TITLE
`ObjWriteError` with large number of batches during insert

### ISSUE THREAD

**Issue by xinifinity** [ava-labs/firewood#532]
https://github.com/ava-labs/firewood/pull/344 introduces a regression that when running insert example with large number of batches it gives `ObjWriteError`,

```
cargo run --release --quiet --example insert --  -n 2000 -b 10 -s 0
thread 'main' panicked at firewood/examples/insert.rs:88:57:
called `Result::unwrap()` on an `Err` value: InternalError(WriteError(ObjWriteError))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by xinifinity** [comment]
Debugged to see what is the cause. It turned out to be the `ObjWriteError` happens for BranchNode whenever try to write to shale, the size of the object exceeds what it is expected to. Specifically, [here](https://github.com/ava-labs/firewood/blob/main/firewood/src/shale/mod.rs#L301-L302). Also attached the screen shot to see the call stack. 
<img width="1484" alt="Screenshot 2024-02-16 at 3 51 24 PM" src="https://github.com/ava-labs/firewood/assets/113067541/c9aa9150-5de0-4ffb-972d-3a3bea7016ae">

**Comment by richardpringle** [comment]
I think we just need to write a new node because I'm guessing it's when the size changes?
