### ISSUE TITLE
Find other places that clone Node and see if we can use `into_inner`

### ISSUE THREAD

**Issue by rkuris** [ava-labs/firewood#549]
There are many other places other than here that could benefit from calling `into_inner`. I don't have time to find them all right now.

_Originally posted by @richardpringle in https://github.com/ava-labs/firewood/pull/548#discussion_r1497656716_

**Comment by richardpringle** [comment]
I would start with the node iterators

**Comment by rkuris** [comment]
Closing this after rearchitecture
