### ISSUE TITLE
Decouple the Storage of Nodes and their Hashes 

### ISSUE THREAD

**Issue by xinifinity** [ava-labs/firewood#576]
While inspecting and improving the WAL layer, I found out even with small writes (e.g. 10 insertions) which should only affect the layout of subtrees with limited number of nodes, as we are storing root hashes/encoding values that triggers dirty pages writes of all the parents nodes of the subtree(s). As the batch size grow up, the dirty pages size grows linearly instead of staying constant. In the end, it will stay with a cap, but still it is like 50 dirty pages vs 2 or 3 dirty pages at the beginning of the batch insertion for 10000 batches.

This actually obey the design of firewood which only generate dirty pages when the node structure is changes. With small insertions we should generate constant size of dirty pages. e.g single digital dirty pages for 10 insertions in each batch. 

To do so, we need to separate out the root hash from the node structure in the shale store layer, and group all root hashes store together, so that node without structure changes stay untouched.

**Comment by rkuris** [comment]
This is no longer relevant with the new implementation.
