### ISSUE TITLE
shale: QOL and observability

### ISSUE THREAD

**Issue by hexfusion** [ava-labs/firewood#69]
This issue covers the following QOL tasks

- [ ] impl Debug for UnsafeCell usage to allow observability of interior objects.
- [x] Improve error handling (cleanup unwraps)
- [ ] Add basic README
- [ ] Add log package and trace logging
- [x] Review making the project more generic
- [ ] Review unsafe usage and add SAFETY notices.
- [x] Add unit tests

**Comment by rkuris** [comment]
Closing in favor of a larger issue.
